stages:
  - test
  - build

unit-test:
  stage: test
  image: python:3.11
  before_script:
    - pip install uv
    - uv sync --dev
  script:
    - uv run pytest

build-package:
  stage: build
  image: python:3.11
  before_script:
    - pip install uv
  script:
    - uv build
  artifacts:
    paths:
      - dist/phycode-*.whl
      - dist/phycode-*.tar.gz
