from pathlib import Path

from phycode.feedback import classify_feedback
from phycode.models import AgentProfile, FeedbackKind, ToolCall, ToolResult
from phycode.policy import PolicyContext
from phycode.tools.base import ToolRegistry, ToolRuntime
from phycode.tools.shell_tools import register_shell_tools


def test_shell_success_maps_to_success_feedback(tmp_path: Path):
    registry = ToolRegistry()
    register_shell_tools(registry, workspace_root=tmp_path, test_command="python --version")
    call = ToolCall(tool_name="shell.run", args={"command": "python --version"})
    runtime_result = ToolRuntime(registry).run(call, PolicyContext(tmp_path, [], True), approved=True)
    feedback = classify_feedback(runtime_result.tool_result)
    assert feedback[0].kind == FeedbackKind.SUCCESS


def test_tool_error_maps_to_tool_error():
    feedback = classify_feedback(ToolResult(tool_call_id="x", status="tool_error", stderr="old text not found"))
    assert feedback[0].kind == FeedbackKind.TOOL_ERROR


def test_prbench_direct_csv_denial_feedback_points_to_script_execution() -> None:
    feedback = classify_feedback(
        ToolResult(
            tool_call_id="direct-csv",
            status="policy_blocked",
            stderr="Expected CSV files must be generated by a reproduction script and process.run",
        ),
        profile=AgentProfile.PRBENCH,
        policy_rule_id="prbench.direct_csv_mutation_blocked",
    )[0]

    assert feedback.kind == FeedbackKind.POLICY_BLOCKED
    assert feedback.retryable is True
    assert feedback.suggested_next_step is not None
    assert (
        "modify or rewrite the reproduction script"
        in feedback.suggested_next_step.casefold()
    )
    assert "process.run" in feedback.suggested_next_step
    assert "Ask the user" not in feedback.suggested_next_step
